name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    env:  # 👈 Add this section
      CAMERA_CONFIG_FILE: backend/camera_config.test.json

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt

      - name: Create test camera config  # 👈 Add this so the test file exists
        run: |
          echo '{
            "cam1": {
              "rtsp_url": "rtsp://example.com/test",
              "device_id": "testcam01"
            }
          }' > camera_config.test.json

      - name: Run unit tests
        run: |
          python -m unittest discover ../tests
