name: ReefCam CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python boto3 flask

      - name: Run Tests
        run: |
          mkdir -p snapshots/tankcam01/$(date +%Y-%m-%d)
          touch snapshots/tankcam01/$(date +%Y-%m-%d)/snapshot_dummy.jpg
          python -m unittest discover -s tests
